[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cwordtm"
authors = [{name = "Johnny Cheng", email = "drjohnnycheng@gmail.com"}]
dynamic = ["version", "description"]
